### ISSUE TITLE
'paste' not working in kakoune inside tmux. 

### ISSUE THREAD

**Issue by StatPal** [alexherbo2/dotfiles#1]
I tried your tmux config file and that helped a lot. 

However, with kakoune inside tmux, after yank, p/P is not working inside tmux. Can you shed some light on this. (I'm new to the tmux and modal editors.) 

Thanks in advance.

**Comment by alexherbo2** [comment]
tmux has 3 values for `set-clipboard` option: `on`, `external` and `off`.  It is `external` by default, which allows tmux to set the clipboard, but prevents applications to set it.  `on` allows both.

``` tmux
# Clipboard
# Allows applications to set the clipboard.
set-option -s set-clipboard on
```

The clipboard is set using the ANSI OSC 52 escape sequence, which can be emitted by applications, such as Kakoune.

In [`lib.kak`] from [kakoune.cr], I implemented like this:

``` kak
# Documentation: https://xfree86.org/current/ctlseqs.html#:~:text=clipboard
define-command -override synchronize-clipboard -docstring 'synchronize clipboard' %{
  remove-hooks global synchronize-clipboard
  hook -group synchronize-clipboard global RegisterModified '"' %{
    nop %sh{
      encoded_selection_data=$(printf '%s' "$kak_main_reg_dquote" | base64)
      printf '\033]52;c;%s\a' "$encoded_selection_data" > /dev/tty
    }
  }
}
```

[kakoune.cr]: https://github.com/alexherbo2/kakoune.cr
[`lib.kak`]: https://github.com/alexherbo2/kakoune.cr/blob/master/share/kcr/rc/lib.kak

and in my [`kakrc`]:

``` kak
# Clipboard
synchronize-clipboard
```

[`kakrc`]: https://github.com/alexherbo2/configuration/blob/master/config/kak/kakrc

You can also find this nice article: [tmux in practice: integration with the system clipboard].

[tmux in practice: integration with the system clipboard]: https://medium.com/free-code-camp/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b

**Comment by StatPal** [comment]
Thank you very much. Sorry, I should have told you that I was working with an ssh-ed terminal. 
Your code helped me with the 'P' part and now my local clipboard is connected and I can paste even with the tmux open. 

However, now yank is not connected with the local(/ssh-ed) clipboard. Whenever I yank something in kakoune, it says something like: 
'yanked 1 selections to register " '
But I can't see it on my clipboard or I can't paste that copied part. I couldn't find the 'lib.kak' file. Do you have anything regarding this?

**Comment by alexherbo2** [comment]
[lib.kak]

[lib.kak]: https://github.com/alexherbo2/lib.kak

**Comment by StatPal** [comment]
Okay, I got the possible reason for the yank problem. It was happening because I used a gnome-terminal in my local computer, which does not support ANSI OSC 52 escape sequence. However, I don't know how the paste worked though. 

Thanks for the lib.kak link. I will look at it more carefully. 

Do you have any suggestions or workarounds with the gnome-terminal(maybe with xclip)? (I looked at your link and that referenced a [more convoluted way](https://medium.com/hackernoon/tmux-in-practice-copy-text-from-remote-session-using-ssh-remote-tunnel-and-systemd-service-dd3c51bca1fa) and also got a [link](https://gitlab.gnome.org/GNOME/vte/-/issues/125) after a search. I am trying other terminals too - like Alacritty.)

**Comment by alexherbo2** [comment]
[Registers & Clipboard]

[Registers & Clipboard]: https://github.com/mawww/kakoune/wiki/Registers---Clipboard

**Comment by StatPal** [comment]
Thanks again. I am looking at this and closing this issue.
