### ISSUE TITLE
kak wrapper should support +line:column

### ISSUE THREAD

**Issue by Delapouite** [alexherbo2/dotfiles#1]
Hello Alex.

In https://github.com/alexherbo2/dotfiles/blob/master/kak/bin/kak there's currently no way to run this shell script optionaly providing line and column numbers (when `$KAK_SESSION` and `$KAK_CLIENT` are set) like
`kak foo +42:10`

I ran into a scenario where I needed this stuff (ripgrep pipe into fzf).

**Comment by alexherbo2** [comment]
I added support to target line and column for the first file.

**Comment by Delapouite** [comment]
thanks, works great !

I'm using it with this script:

```sh
#!/bin/sh
# used by kakoune

# --select-1: auto-select the only match
# --multi: use <tab> to select multiple files
# --delimiter: to separate the filename from the match
rg $KAK_OPT_RG_QUERY \
  --column \
  --line-number \
  --color=always \
| fzf \
  --ansi \
  --select-1 \
  --multi \
  --delimiter : \
  --nth 1 \
  --preview="~/bin/preview.rb {1}:{2}" \
  --preview-window=right:50% \
| cut -d : -f 1,2,3 \
| awk -F : '{ print $1 " +"$2":"$3 }' \
| xargs $EDITOR
```
